/*******************************************************/
/**  Autogenerated lexicon entry file from cmu_time_awb    */
/*******************************************************/

#include "cst_string.h"

#include "cst_lexicon.h"

extern const unsigned char cmu_time_awb_lex_phones[];
const lexicon_entry cmu_time_awb_lex_entry[] = 
{
    { "da", 0 },
    { "iafter", 2 },
    { "nafternoon", 7 },
    { "ralmost", 15 },
    { "ceight", 22 },
    { "celeven", 25 },
    { "nevening", 32 },
    { "rexactly", 38 },
    { "cfive", 47 },
    { "cfour", 51 },
    { "dhalf", 55 },
    { "iin", 59 },
    { "vis", 62 },
    { "rjust", 65 },
    { "jlittle", 70 },
    { "nmidnight", 76 },
    { "nmorning", 83 },
    { "cnine", 90 },
    { "rnow", 94 },
    { "cone", 97 },
    { "npast", 101 },
    { "nquarter", 106 },
    { "cseven", 113 },
    { "csix", 119 },
    { "cten", 124 },
    { "dthe", 128 },
    { "cthree", 131 },
    { "ntime", 135 },
    { "tto", 139 },
    { "ctwelve", 142 },
    { "ctwenty", 148 },
    { "ctwo", 155 },
    { NULL, 0 } 
};


const int cmu_time_awb_num_entries = 32;

const char * const cmu_time_awb_phone_table[36] = 
{
    "_epsilon_",
    "ax",
    "ae1",
    "f",
    "t",
    "er",
    "n",
    "uw",
    "ao1",
    "l",
    "m",
    "ow1",
    "s",
    "ey1",
    "ih",
    "eh1",
    "v",
    "iy1",
    "ng",
    "g",
    "z",
    "k",
    "iy",
    "ay",
    "r",
    "hh",
    "ih1",
    "jh",
    "ah1",
    "d",
    "aw1",
    "w",
    "p",
    "dh",
    "th",
    NULL
};

