/*******************************************************/
/**  Autogenerated cart tree for us_phrasing    */
/**  from .    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"punc");
DEF_STATIC_CONST_VAL_STRING(val_0001,"BB");
#define CTNODE_us_phrasing_NO_0000 2
DEF_STATIC_CONST_VAL_STRING(val_0002,"NB");
#define CTNODE_us_phrasing_NO_0002 4
DEF_STATIC_CONST_VAL_STRING(val_0003,"content");
#define CTNODE_us_phrasing_NO_0006 8
DEF_STATIC_CONST_VAL_STRING(val_0004,"0");
#define CTNODE_us_phrasing_NO_0008 10
DEF_STATIC_CONST_VAL_STRING(val_0005,"in");
#define CTNODE_us_phrasing_NO_0010 12
#define CTNODE_us_phrasing_NO_0012 14
DEF_STATIC_CONST_VAL_STRING(val_0006,"det");
#define CTNODE_us_phrasing_NO_0014 16
#define CTNODE_us_phrasing_NO_0005 17
#define CTNODE_us_phrasing_NO_0017 19
#define CTNODE_us_phrasing_NO_0019 21
#define CTNODE_us_phrasing_NO_0021 23
#define CTNODE_us_phrasing_NO_0023 25
#define CTNODE_us_phrasing_NO_0025 27
#define CTNODE_us_phrasing_NO_0028 30
#define CTNODE_us_phrasing_NO_0030 32
DEF_STATIC_CONST_VAL_STRING(val_0007,"aux");
#define CTNODE_us_phrasing_NO_0032 34
#define CTNODE_us_phrasing_NO_0027 35
#define CTNODE_us_phrasing_NO_0035 37
#define CTNODE_us_phrasing_NO_0004 38
